use_frameworks!
target 'SwaggerClientSupport_Tests' do
  pod 'OBSwaggerClientSupport/Promise', :path => '../'
  pod 'OBSwaggerClientSupport/RxSwift', :path => '../'
  pod 'OBSwaggerClientSupport/Accept-Language', :path => '../'
  
  # Replace this with your own SwaggerClient pod.
  pod 'SwaggerClient', :path => './swift4-client-generated'
  
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
end
